
cucumber.features=src/test/resources/features

cucumber.glue=com.proyecto.stepdefinitions

cucumber.plugin=pretty,\
  json:target/cucumber-reports/Cucumber.json,\
  html:target/cucumber-reports/Cucumber.html