# Serenity
serenity.project.name=Pruebas SOAP
serenity.report.format = junit
serenity.junit.outputDirectory = target/site/serenity

# URL del servicio SOAP
soap.base.url=http://www.dneonline.com/calculator.asmx

# Cucumber
cucumber.features=src/test/resources/features
cucumber.glue=com.proyecto.stepdefinitions
cucumber.plugin=pretty,\
  json:target/cucumber-reports/Cucumber.json,\
  html:target/cucumber-reports/Cucumber.html